### ISSUE TITLE
App shutting down on opening

### ISSUE THREAD

**Issue by NeetBux-Hash** [Gallardo994/SplinterCellBlacklistFpsFix#2]
Is there supposed to be an application or command window running when i run the exe? I dont know if it even works bc i click the exe and theres only a brief second of an app trying to open but closes again. Dont see any processes running either. On w11

**Comment by m-navarro** [comment]
> Is there supposed to be an application or command window running when i run the exe? I dont know if it even works bc i click the exe and theres only a brief second of an app trying to open but closes again. Dont see any processes running either. On w11

@NeetBux-Hash 
It should open a console window with the phrase "Process: Blacklist_DX11_game". You must leave the window open for the application to find and fix your running instance of Splinter Cell Blacklist. If it's not staying open then I would recommend trying to install the Microsoft .NET 7 runtimes onto your system. You should be able to download the different runtime versions from Microsoft's website: https://dotnet.microsoft.com/en-us/download/dotnet/7.0

**Comment by NeetBux-Hash** [comment]
Got it to stay open. Forgot to mention I'm using it for SC conviction. Works incredibly well
